### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by YouthsSonic** [R3nzTheCodeGOD/Valorant-External-Cheat#23]
It doesnt work pls help

**Comment by R3nzTheCodeGOD** [comment]
## what exactly is not working.
**if the program does not crash and does not work, try again in windowed full screen mode**

**Comment by YouthsSonic** [comment]
It just doesn’t auto shoot

**Comment by R3nzTheCodeGOD** [comment]
## Issue #23
**There are answers to solve the problem easily.**
- The operating system you are using ?
- Are you using the source code or the compiled version?
- If you're using the source code, did you make any changes?
- If you are using the source code, which python version are you using?
- The resolution you use on your desktop ?
- The resolution you use in-game ?

**Note:** In-game and desktop resolution must be the same

_**I think the problem is not software related but usage related, I am waiting for your answer to understand the problem.**_

**Comment by YouthsSonic** [comment]
I use the resolution 1280x760 and on Windows I haven’t changed the code.

**Comment by YouthsSonic** [comment]
It’s 1280x760 on valorant

**Comment by YouthsSonic** [comment]
Pls help I rly need it
